# provide default environment name
name: pytemplate

# conda-forge used only if packages not found in defaults
channels:
  - defaults
  - conda-forge

# add all development time conda packages here
# package dependencies should be in setup.cfg instead
# package will be installed locally with pip -e and afterwards can be treated as any other package
# if you change something in the package's code you don't have to install the package again
# that's because locally the code is accessed directly from the source
dependencies:
  - python==3.9.2
  - pip==21.0.1
  - pip:
      - -e pytemplate