name: Workflow for deploying docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pytemplate
          environment-file: environment.yml
      - name: Install package
        working-directory: pytemplate
        # Sadly we need to install the package, waiting for https://github.com/python-poetry/poetry/issues/1644
        run: poetry install --no-root --extras docs
      - name: Deploy docs
        run: mkdocs gh-deploy --force