name: Workflow for running tests

on:
  push:
    branches:
      - main
    paths:
      - 'pytemplate/**'
      - 'environment.yml'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'pytemplate/**'
      - 'environment.yml'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        config:
          - { os: ubuntu-20.04, shell: bash -l }
          - { os: macos-10.15, shell: bash -l }
          - { os: windows-2019, shell: cmd /C CALL }
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: ${{ matrix.config.shell }} {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pytemplate
          environment-file: environment.yml
      - name: Install package
        working-directory: pytemplate
        # workaround for non-editable install, waiting for https://github.com/python-poetry/poetry/issues/1382
        run: |
          poetry build -f wheel
          pip install --find-links=dist pytemplate[test]
      - name: Run tests
        run: pytest pytemplate