name: Workflow on push

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pytemplate-docs
          environment-file: environments/docs.yml
      - name: Deploy docs
        run: mkdocs gh-deploy --force